export enum FixtureStatuses {
  NS = 'NS',
  LIVE = 'LIVE',
  HT = 'HT',
  FT = 'FT',
  ET = 'ET',
  PEN_LIVE = 'PEN_LIVE',
  AET = 'AET',
  BREAK = 'BREAK',
  FT_PEN = 'FT_PEN',
  CANCL = 'CANCL',
  POSTP = 'POSTP',
  INT = 'INT',
  ABAN = 'ABAN',
  SUSP = 'SUSP',
  AWARDED = 'AWARDED',
  DELAYED = 'DELAYED',
  TBA = 'TBA',
  WO = 'WO',
  AU = 'AU',
  Deleted = 'Deleted',
}
