export enum Sections {
  category = 'category',
  football = 'football',
  livescore = 'livescore',
  results = 'results',
  fixtures = 'fixtures',
  ranking = 'ranking',
  thailandRanking = 'thailand-ranking',
  footballNews = 'football-news',
  posts = 'posts',
  footballHighlights = 'football-highlights',
  highlights = 'highlights',
  tag = 'tag',
  tags = 'tags',
  worldCup2022 = 'world-cup-2022',
  prediction = 'prediction',
  thaiFixtures = 'thai-fixtures',
  thaiResults = 'thai-results',
  thaiLivescore = 'thai-livescore',
}
